export const projects = [
  {
    id: 101,
    category: "React",
    theme: "dark",
    title: "Admin Dashboard",
    description:
      "A beautiful Admin Dashboard with a light&dark theme using React & Tailwind.",
    image:
      "https://res.cloudinary.com/dfrst7wxq/image/upload/v1777932342/project101_zjslmk.png",
    tags: ["React", "Tailwind"],
    demoUrl: "https://admin-dashboard-coral-eight-10.vercel.app/",
    githubUrl: "https://github.com/ahmedaldailami/Admin-Dashboard.git",
  },
  {
    id: 102,
    category: "React",
    theme: "dark",
    title: "Perfect Vault",
    description:
      "A beautiful Vault Dashboard with a light&dark theme using React & Tailwind.",
    image:
      "https://res.cloudinary.com/dfrst7wxq/image/upload/v1777932342/project102_f6kfex.png",
    tags: ["React", "Tailwind"],
    demoUrl: "https://perfectvault2.vercel.app/",
    githubUrl: "https://github.com/ahmedaldailami/Perfect-Vault.git",
  },
  {
    id: 1,
    category: "React",
    theme: "dark",
    title: "Portfolio",
    description:
      "A beautiful Portfolio page with a light&dark theme using React & Tailwind.",
    image:
      "https://res.cloudinary.com/dfrst7wxq/image/upload/v1777932335/project1_pv0jhq.png",
    tags: ["React", "Tailwind"],
    demoUrl: "https://simple-portfolio-five-omega.vercel.app/",
    githubUrl: "https://github.com/ahmedaldailami/React-Portfolio.git",
  },
  {
    id: 2,
    category: "React",
    theme: "light",
    title: "E-commerce website",
    description:
      "A beautiful E-commerce website with Cart & faivurites It also has a landing page.",
    image:
      "https://res.cloudinary.com/dfrst7wxq/image/upload/v1777932336/project2_aefze1.png",
    tags: ["React", "Tailwind", "API"],
    demoUrl: "https://e-commerce-bay-six-96.vercel.app/",
    githubUrl: "https://github.com/ahmedaldailami/eCommerce.git",
  },
  {
    id: 3,
    category: "React",
    theme: "light",
    title: "Resturent Website",
    description:
      "A beautiful Resturent ordering Website app using React & Tailwind.",
    image:
      "https://res.cloudinary.com/dfrst7wxq/image/upload/v1777932339/project3_ikeadq.png",
    tags: ["React", "Tailwind", "API"],
    demoUrl: "https://ordering-oaa5axoa1-ahmedaldailamis-projects.vercel.app/",
    githubUrl: "https://github.com/ahmedaldailami/Ordering-App.git",
  },
  {
    id: 4,
    category: "React",
    theme: "dark",
    title: "Najd Constructing",
    description: "A beautiful landing page app using Tailwind.",
    image:
      "https://res.cloudinary.com/dfrst7wxq/image/upload/v1777932335/project4_surigd.png",
    tags: ["React", "Tailwind"],
    demoUrl: "https://contracting-compony-c4pv.vercel.app/",
    githubUrl: "https://github.com/ahmedaldailami/Contracting-Compony.git",
  },
  {
    id: 5,
    category: "React",
    theme: "dark",
    title: "ToDo List",
    description: "A beautiful landing page app using Tailwind.",
    image:
      "https://res.cloudinary.com/dfrst7wxq/image/upload/v1777932335/project5_dwja2c.png",
    tags: ["React", "Tailwind"],
    demoUrl: "https://to-do-app-six-mu-95.vercel.app/",
    githubUrl: "https://github.com/ahmedaldailami/ToDo-App.git",
  },
  {
    id: 6,
    category: "React",
    theme: "dark",
    title: "Note App",
    description: "A beautiful Note app using React & Tailwind.",
    image:
      "https://res.cloudinary.com/dfrst7wxq/image/upload/v1777932336/project6_bdz5gm.png",
    tags: ["React", "Tailwind"],
    demoUrl: "https://github.com/ahmedaldailami/Note-App2.git",
    githubUrl: "https://github.com/ahmedaldailami/Note-App2.git",
  },
  {
    id: 7,
    category: "JS",
    theme: "dark",
    title: "Cruds system",
    description: "A beautiful landing page app using Tailwind.",
    image:
      "https://res.cloudinary.com/dfrst7wxq/image/upload/v1777932336/project7_h6e2iv.png",
    tags: ["Js"],
    demoUrl: "https://ahmedaldailami.github.io/CRUDS/",
    githubUrl: "https://github.com/ahmedaldailami/CRUDS.git",
  },
  {
    id: 8,
    category: "HTML&CSS",
    theme: "dark",
    title: "Perfect Design",
    description: "A beautiful landing page app using Bootstrab.",
    image:
      "https://res.cloudinary.com/dfrst7wxq/image/upload/v1777932338/project8_zrpuel.png",
    tags: ["HTML&CSS", "Bootstrab"],
    demoUrl: "https://ahmedaldailami.github.io/Perfect-Design/",
    githubUrl: "https://github.com/ahmedaldailami/Perfect-Design.git",
  },
  // {
  //   id: 9,
  //   category: "HTML&CSS",
  //   theme: "dark",
  //   title: "landing page",
  //   description: "A beautiful landing page app using Tailwind.",
  //   image: "/projects/project9.png",
  //   tags: ["HTML&CSS", "Bootstrab"],
  //   demoUrl: "https://moviesrecommendation1.netlify.app/",
  //   githubUrl: "https://github.com/anassultanali/React-Movies-Recommendation",
  // },

  {
    id: 11,
    category: "HTML&CSS",
    theme: "light",
    title: "landing page",
    description: "A beautiful landing page app using Tailwind.",
    image:
      "https://res.cloudinary.com/dfrst7wxq/image/upload/v1777932339/project11_lz2saa.png",
    tags: ["HTML&CSS"],
    demoUrl: "https://ahmedaldailami.github.io/projectz3/",
    githubUrl: "https://github.com/ahmedaldailami/projectz3.git",
  },
  {
    id: 12,
    category: "HTML&CSS",
    theme: "dark",
    title: "landing page",
    description: "A beautiful landing page app using Tailwind.",
    image:
      "https://res.cloudinary.com/dfrst7wxq/image/upload/v1777932342/project12_st4wgq.png",
    tags: ["HTML&CSS"],
    demoUrl: "https://ahmedaldailami.github.io/projectz2/",
    githubUrl: "https://github.com/ahmedaldailami/projectz2.git",
  },
  {
    id: 13,
    category: "HTML&CSS",
    theme: "dark",
    title: "landing page",
    description: "A beautiful landing page app using Tailwind.",
    image:
      "https://res.cloudinary.com/dfrst7wxq/image/upload/v1777932339/project13_ncnigr.png",
    tags: ["HTML&CSS"],
    demoUrl: "https://ahmedaldailami.github.io/projectz1/",
    githubUrl: "https://github.com/ahmedaldailami/projectz1.git",
  },
  {
    id: 14,
    category: "HTML&CSS",
    theme: "dark",
    title: "landing page",
    description: "A beautiful landing page app using Tailwind.",
    image:
      "https://res.cloudinary.com/dfrst7wxq/image/upload/v1777932341/project14_vsh8i4.png",
    tags: ["HTML&CSS"],
    demoUrl: "https://ahmedaldailami.github.io/projectz1/",
    githubUrl: "https://github.com/ahmedaldailami/projectz1.git",
  },
  {
    id: 15,
    category: "HTML&CSS",
    theme: "dark",
    title: "Flipping Signin & Login",
    description: "A beautiful landing page app using Tailwind.",
    image:
      "https://res.cloudinary.com/dfrst7wxq/image/upload/v1777932341/project15_hyl5ee.png",
    tags: ["HTML&CSS"],
    demoUrl: "https://moviesrecommendation1.netlify.app/",
    githubUrl: "https://github.com/anassultanali/React-Movies-Recommendation",
  },
  {
    id: 16,
    category: "HTML&CSS",
    theme: "dark",
    title: "Lighting Signin & Login",
    description: "A beautiful landing page app using Tailwind.",
    image:
      "https://res.cloudinary.com/dfrst7wxq/image/upload/v1777932340/project16_ctqrem.png",
    tags: ["HTML&CSS"],
    demoUrl: "https://moviesrecommendation1.netlify.app/",
    githubUrl: "https://github.com/anassultanali/React-Movies-Recommendation",
  },
  {
    id: 17,
    category: "JS",
    theme: "dark",
    title: "Browser Extensions",
    description: "A beautiful landing page app using Tailwind.",
    image:
      "https://res.cloudinary.com/dfrst7wxq/image/upload/v1777932341/project17_ppxclj.png",
    tags: ["HTML&CSS", "JS"],
    demoUrl: "https://moviesrecommendation1.netlify.app/",
    githubUrl: "https://github.com/anassultanali/React-Movies-Recommendation",
  },
];
