  export const projects = [
    {
      id: 101,
      category: "React",
      theme: "dark",
      title: "Admin Dashboard",
      description:
        "A beautiful Admin Dashboard with a light&dark theme using React & Tailwind.",
      image: "/projects/project101.png",
      tags: ["React", "Tailwind"],
      demoUrl: "https://admin-dashboard-coral-eight-10.vercel.app/",
      githubUrl: "https://github.com/ahmedaldailami/Admin-Dashboard.git",
    },
    {
      id: 102,
      category: "React",
      theme: "dark",
      title: "Perfect Vault",
      description:
        "A beautiful Vault Dashboard with a light&dark theme using React & Tailwind.",
      image: "/projects/project102.png",
      tags: ["React", "Tailwind"],
      demoUrl: "https://perfectvault2.vercel.app/",
      githubUrl: "https://github.com/ahmedaldailami/Perfect-Vault.git",
    },
    {
      id: 1,
      category: "React",
      theme: "dark",
      title: "Portfolio",
      description:
        "A beautiful Portfolio page with a light&dark theme using React & Tailwind.",
      image: "/projects/project1.png",
      tags: ["React", "Tailwind"],
      demoUrl: "https://anassultanali.github.io/Mohamed-Ali-Club/",
      githubUrl: "https://github.com/anassultanali/Mohamed-Ali-Club",
    },
    {
      id: 2,
      category: "React",
      theme: "light",
      title: "E-commerce website",
      description:
        "A beautiful E-commerce website with Cart & faivurites It also has a landing page.",
      image: "/projects/project2.png",
      tags: ["React", "Tailwind", "API"],
      demoUrl: "https://e-commerce-bay-six-96.vercel.app/",
      githubUrl: "https://github.com/ahmedaldailami/eCommerce.git",
    },
    {
      id: 3,
      category: "React",
      theme: "light",
      title: "Resturent Website",
      description:
        "A beautiful Resturent ordering Website app using React & Tailwind.",
      image: "/projects/project3.png",
      tags: ["React", "Tailwind", "API"],
      demoUrl:
        "https://ordering-oaa5axoa1-ahmedaldailamis-projects.vercel.app/",
      githubUrl: "https://github.com/ahmedaldailami/Ordering-App.git",
    },
    {
      id: 4,
      category: "React",
      theme: "dark",
      title: "Najd Constructing",
      description: "A beautiful landing page app using Tailwind.",
      image: "/projects/project4.png",
      tags: ["React", "Tailwind"],
      demoUrl: "https://contracting-compony-c4pv.vercel.app/",
      githubUrl: "https://github.com/ahmedaldailami/Contracting-Compony.git",
    },
    {
      id: 5,
      category: "React",
      theme: "dark",
      title: "ToDo List",
      description: "A beautiful landing page app using Tailwind.",
      image: "/projects/project5.png",
      tags: ["React", "Tailwind"],
      demoUrl: "https://moviesrecommendation1.netlify.app/",
      githubUrl: "https://github.com/anassultanali/React-Movies-Recommendation",
    },
    {
      id: 6,
      category: "React",
      theme: "dark",
      title: "Note App",
      description: "A beautiful landing page app using Tailwind.",
      image: "/projects/project6.png",
      tags: ["React", "Tailwind"],
      demoUrl: "https://moviesrecommendation1.netlify.app/",
      githubUrl: "https://github.com/anassultanali/React-Movies-Recommendation",
    },
    {
      id: 7,
      category: "JS",
      theme: "dark",
      title: "Cruds system",
      description: "A beautiful landing page app using Tailwind.",
      image: "/projects/project7.png",
      tags: ["Js"],
      demoUrl: "https://moviesrecommendation1.netlify.app/",
      githubUrl: "https://github.com/ahmedaldailami/CRUDS.git",
    },
    {
      id: 8,
      category: "HTML&CSS",
      theme: "dark",
      title: "Perfect Design",
      description: "A beautiful landing page app using Bootstrab.",
      image: "/projects/project8.png",
      tags: ["HTML&CSS", "Bootstrab"],
      demoUrl: "https://ahmedaldailami.github.io/Perfect-Design/",
      githubUrl: "https://github.com/anassultanali/React-Movies-Recommendation",
    },
    {
      id: 9,
      category: "HTML&CSS",
      theme: "dark",
      title: "landing page",
      description: "A beautiful landing page app using Tailwind.",
      image: "/projects/project9.png",
      tags: ["HTML&CSS", "Bootstrab"],
      demoUrl: "https://moviesrecommendation1.netlify.app/",
      githubUrl: "https://github.com/anassultanali/React-Movies-Recommendation",
    },

    {
      id: 11,
      category: "HTML&CSS",
      theme: "light",
      title: "landing page",
      description: "A beautiful landing page app using Tailwind.",
      image: "/projects/project11.png",
      tags: ["HTML&CSS"],
      demoUrl: "https://moviesrecommendation1.netlify.app/",
      githubUrl: "https://github.com/anassultanali/React-Movies-Recommendation",
    },
    {
      id: 12,
      category: "HTML&CSS",
      theme: "dark",
      title: "landing page",
      description: "A beautiful landing page app using Tailwind.",
      image: "/projects/project12.png",
      tags: ["HTML&CSS"],
      demoUrl: "https://moviesrecommendation1.netlify.app/",
      githubUrl: "https://github.com/anassultanali/React-Movies-Recommendation",
    },
    {
      id: 13,
      category: "HTML&CSS",
      theme: "dark",
      title: "landing page",
      description: "A beautiful landing page app using Tailwind.",
      image: "/projects/project13.png",
      tags: ["HTML&CSS"],
      demoUrl: "https://moviesrecommendation1.netlify.app/",
      githubUrl: "https://github.com/anassultanali/React-Movies-Recommendation",
    },
    {
      id: 14,
      category: "HTML&CSS",
      theme: "dark",
      title: "landing page",
      description: "A beautiful landing page app using Tailwind.",
      image: "/projects/project14.png",
      tags: ["HTML&CSS"],
      demoUrl: "https://moviesrecommendation1.netlify.app/",
      githubUrl: "https://github.com/anassultanali/React-Movies-Recommendation",
    },
    {
      id: 15,
      category: "HTML&CSS",
      theme: "dark",
      title: "Flipping Signin & Login",
      description: "A beautiful landing page app using Tailwind.",
      image: "/projects/project15.png",
      tags: ["HTML&CSS"],
      demoUrl: "https://moviesrecommendation1.netlify.app/",
      githubUrl: "https://github.com/anassultanali/React-Movies-Recommendation",
    },
    {
      id: 16,
      category: "HTML&CSS",
      theme: "dark",
      title: "Lighting Signin & Login",
      description: "A beautiful landing page app using Tailwind.",
      image: "/projects/project16.png",
      tags: ["HTML&CSS"],
      demoUrl: "https://moviesrecommendation1.netlify.app/",
      githubUrl: "https://github.com/anassultanali/React-Movies-Recommendation",
    },
    {
      id: 17,
      category: "JS",
      theme: "dark",
      title: "Browser Extensions",
      description: "A beautiful landing page app using Tailwind.",
      image: "/projects/project17.png",
      tags: ["HTML&CSS", "JS"],
      demoUrl: "https://moviesrecommendation1.netlify.app/",
      githubUrl: "https://github.com/anassultanali/React-Movies-Recommendation",
    },
  ];