  export const projects = [
    {
      id: 1,
      category: "React",
      theme: "dark",
      title: "Portfolio",
      description: "A beautiful Portfolio page with a light&dark theme using React & Tailwind.",
      image: "/projects/project1.png",
      tags: ["React", "Tailwind"],
      demoUrl: "https://anassultanali.github.io/Mohamed-Ali-Club/",
      githubUrl: "https://github.com/anassultanali/Mohamed-Ali-Club",
    },
    {
      id: 2,
      category: "React",
      theme: "light",
      title: "E-commerce website",
      description: "A beautiful E-commerce website with Cart & faivurites It also has a landing page.",
      image: "/projects/project2.png",
      tags: ["React","Tailwind", "API"],
      demoUrl: "https://anassultanali.github.io/Landing_page_tailwind/",
      githubUrl: "https://github.com/anassultanali/Landing_page_tailwind",
    },
    {
      id: 3,
      category: "React",
      theme: "light",
      title: "Resturent Website",
      description: "A beautiful landing page app using Tailwind.",
      image: "/projects/project3.png",
      tags: ["React", "Tailwind", "API"],
      demoUrl: "https://moviesrecommendation1.netlify.app/",
      githubUrl: "https://github.com/anassultanali/React-Movies-Recommendation",
    },
    {
      id: 4,
      category: "React",
      theme: "dark",
      title: "Najd Constructing",
      description: "A beautiful landing page app using Tailwind.",
      image: "/projects/project4.png",
      tags: ["React", "Tailwind"],
      demoUrl: "https://moviesrecommendation1.netlify.app/",
      githubUrl: "https://github.com/anassultanali/React-Movies-Recommendation",
    },
    {
      id: 5,
      category: "React",
      theme: "dark",
      title: "ToDo List",
      description: "A beautiful landing page app using Tailwind.",
      image: "/projects/project5.png",
      tags: ["React", "Tailwind"],
      demoUrl: "https://moviesrecommendation1.netlify.app/",
      githubUrl: "https://github.com/anassultanali/React-Movies-Recommendation",
    },
    {
      id: 6,
      category: "React",
      theme: "dark",
      title: "Note App",
      description: "A beautiful landing page app using Tailwind.",
      image: "/projects/project6.png",
      tags: ["React", "Tailwind"],
      demoUrl: "https://moviesrecommendation1.netlify.app/",
      githubUrl: "https://github.com/anassultanali/React-Movies-Recommendation",
    },
    {
      id: 7,
      category: "JS",
      theme: "dark",
      title: "Cruds system",
      description: "A beautiful landing page app using Tailwind.",
      image: "/projects/project7.png",
      tags: ["Js"],
      demoUrl: "https://moviesrecommendation1.netlify.app/",
      githubUrl: "https://github.com/anassultanali/React-Movies-Recommendation",
    },
    {
      id: 8,
      category: "HTML&CSS",
      theme: "dark",
      title: "landing page",
      description: "A beautiful landing page app using Tailwind.",
      image: "/projects/project8.png",
      tags: ["HTML&CSS", "Bootstrab"],
      demoUrl: "https://moviesrecommendation1.netlify.app/",
      githubUrl: "https://github.com/anassultanali/React-Movies-Recommendation",
    },
    {
      id: 9,
      category: "HTML&CSS",
      theme: "dark",
      title: "landing page",
      description: "A beautiful landing page app using Tailwind.",
      image: "/projects/project9.png",
      tags: ["HTML&CSS", "Bootstrab"],
      demoUrl: "https://moviesrecommendation1.netlify.app/",
      githubUrl: "https://github.com/anassultanali/React-Movies-Recommendation",
    },
   
    {
      id: 11,
      category: "HTML&CSS",
      theme: "light",
      title: "landing page",
      description: "A beautiful landing page app using Tailwind.",
      image: "/projects/project11.png",
      tags: ["HTML&CSS"],
      demoUrl: "https://moviesrecommendation1.netlify.app/",
      githubUrl: "https://github.com/anassultanali/React-Movies-Recommendation",
    },
    {
      id: 12,
      category: "HTML&CSS",
      theme: "dark",
      title: "landing page",
      description: "A beautiful landing page app using Tailwind.",
      image: "/projects/project12.png",
      tags: ["HTML&CSS"],
      demoUrl: "https://moviesrecommendation1.netlify.app/",
      githubUrl: "https://github.com/anassultanali/React-Movies-Recommendation",
    },
    {
      id: 13,
      category: "HTML&CSS",
      theme: "dark",
      title: "landing page",
      description: "A beautiful landing page app using Tailwind.",
      image: "/projects/project13.png",
      tags: ["HTML&CSS"],
      demoUrl: "https://moviesrecommendation1.netlify.app/",
      githubUrl: "https://github.com/anassultanali/React-Movies-Recommendation",
    },
    {
      id: 14,
      category: "HTML&CSS",
      theme: "dark",
      title: "landing page",
      description: "A beautiful landing page app using Tailwind.",
      image: "/projects/project14.png",
      tags: ["HTML&CSS"],
      demoUrl: "https://moviesrecommendation1.netlify.app/",
      githubUrl: "https://github.com/anassultanali/React-Movies-Recommendation",
    },
    {
      id: 15,
      category: "HTML&CSS",
      theme: "dark",
      title: "Flipping Signin & Login",
      description: "A beautiful landing page app using Tailwind.",
      image: "/projects/project15.png",
      tags: ["HTML&CSS"],
      demoUrl: "https://moviesrecommendation1.netlify.app/",
      githubUrl: "https://github.com/anassultanali/React-Movies-Recommendation",
    },
    {
      id: 16,
      category: "HTML&CSS",
      theme: "dark",
      title: "Lighting Signin & Login",
      description: "A beautiful landing page app using Tailwind.",
      image: "/projects/project16.png",
      tags: ["HTML&CSS"],
      demoUrl: "https://moviesrecommendation1.netlify.app/",
      githubUrl: "https://github.com/anassultanali/React-Movies-Recommendation",
    },
    {
      id: 17,
      category: "JS",
      theme: "dark",
      title: "Browser Extensions",
      description: "A beautiful landing page app using Tailwind.",
      image: "/projects/project17.png",
      tags: ["HTML&CSS", "JS"],
      demoUrl: "https://moviesrecommendation1.netlify.app/",
      githubUrl: "https://github.com/anassultanali/React-Movies-Recommendation",
    },
  ];